### ISSUE TITLE
README.md中有一个小错误

### ISSUE THREAD

**Issue by fengzhi** [JanHuang/container#1]
$container = new FastD\Container\Container();

$container
    ->injectOn('date', ConstructorInjection::class)
    ->withConstruct()
    ->withArguments([
        new DateTime(),
    ]);

$date = $container->get('date');
这里是不是应该是 $obj = $container->get('date');
echo $obj->date; // (new DateTime())->format(DateTime::W3C)

**Comment by JanHuang** [comment]
好的，感谢反馈🙏
